In [ ]:
import torch
x=torch.tensor(3.0,requires_grad=True)

In [ ]:
y=x**2
x

tensor(3., requires_grad=True)

In [ ]:
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(6.)

In [ ]:
x=torch.tensor(3.0,requires_grad=True)
y=x**2
z=torch.sin(y)
z.backward()
x.grad

tensor(-5.4668)

In [1]:
import torch

In [2]:
x=torch.tensor(6.7)
y=torch.tensor(0.0)

In [3]:
w=torch.tensor(1.0,requires_grad=True)
b=torch.tensor(0.0,requires_grad=True)

In [6]:
w

tensor(1., requires_grad=True)

In [8]:
import torch.nn.functional as F

z=w*x+b
y_pred=torch.sigmoid(z)
loss=F.binary_cross_entropy(y_pred,y)
loss

tensor(6.7012, grad_fn=<BinaryCrossEntropyBackward0>)

In [9]:
loss.backward()

In [10]:
print(w.grad)
print(b.grad)

tensor(6.6918)
tensor(0.9988)


In [14]:
x=torch.tensor([1.0, 2.0, 3.0],requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [27]:
y=(x**2).mean()

In [28]:
y.backward()

In [29]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

In [26]:
# clearing grad
x.grad.zero_()

tensor([0., 0., 0.])

Disabling the gradient calculation


In [30]:
x=torch.tensor(3.0,requires_grad=True)
# y=torch.tensor(2.0,requires_grad=True
x

tensor(3., requires_grad=True)

In [31]:
with torch.no_grad():
    y=x**2


In [32]:
y

tensor(9.)

In [ ]:
y.backward()
# now this will not work