In [1]:
import numpy as np

docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [3]:
import tensorflow
from tensorflow import keras

In [5]:
from tensorflow.keras.layers import TextVectorization
vectorizer = TextVectorization(output_sequence_length=5, standardize='lower_and_strip_punctuation')
vectorizer.adapt(docs)

In [7]:
vectorized_docs = vectorizer(docs)
display(vectorized_docs)

<tf.Tensor: shape=(10, 5), dtype=int64, numpy=
array([[16,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 8,  8, 15,  0,  0],
       [ 3, 18,  3,  2,  3],
       [17, 12,  6,  7,  0],
       [ 5,  5,  0,  0,  0],
       [ 4,  4,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [11, 13,  6,  7,  0],
       [14, 10,  0,  0,  0]])>

In [9]:
vocabulary = vectorizer.get_vocabulary()
display(vocabulary)

['',
 '[UNK]',
 np.str_('india'),
 np.str_('jeetega'),
 np.str_('sachin'),
 np.str_('kohli'),
 np.str_('ki'),
 np.str_('jai'),
 np.str_('hip'),
 np.str_('dhoni'),
 np.str_('zindabad'),
 np.str_('modi'),
 np.str_('mata'),
 np.str_('ji'),
 np.str_('inquilab'),
 np.str_('hurray'),
 np.str_('go'),
 np.str_('bharat'),
 np.str_('bhai')]

In [11]:
# vectorizer.document_count # This attribute does not exist on TextVectorization

In [13]:
sequences = vectorizer(docs)
display(sequences)

<tf.Tensor: shape=(10, 5), dtype=int64, numpy=
array([[16,  2,  0,  0,  0],
       [ 2,  2,  0,  0,  0],
       [ 8,  8, 15,  0,  0],
       [ 3, 18,  3,  2,  3],
       [17, 12,  6,  7,  0],
       [ 5,  5,  0,  0,  0],
       [ 4,  4,  0,  0,  0],
       [ 9,  9,  0,  0,  0],
       [11, 13,  6,  7,  0],
       [14, 10,  0,  0,  0]])>

In [23]:
from keras.datasets import imdb

In [24]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

In [25]:
X_train.shape

(25000,)

In [26]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [27]:
print(len(X_train[0]))
print(len(X_train[1]))

218
189


In [28]:
X_train=keras.preprocessing.sequence.pad_sequences(X_train,maxlen=200,padding='post')
X_test=keras.preprocessing.sequence.pad_sequences(X_test,maxlen=200,padding='post')


In [29]:
X_train[0]

array([    5,    25,   100,    43,   838,   112,    50,   670, 22665,
           9,    35,   480,   284,     5,   150,     4,   172,   112,
         167, 21631,   336,   385,    39,     4,   172,  4536,  1111,
          17,   546,    38,    13,   447,     4,   192,    50,    16,
           6,   147,  2025,    19,    14,    22,     4,  1920,  4613,
         469,     4,    22,    71,    87,    12,    16,    43,   530,
          38,    76,    15,    13,  1247,     4,    22,    17,   515,
          17,    12,    16,   626,    18, 19193,     5,    62,   386,
          12,     8,   316,     8,   106,     5,     4,  2223,  5244,
          16,   480,    66,  3785,    33,     4,   130,    12,    16,
          38,   619,     5,    25,   124,    51,    36,   135,    48,
          25,  1415,    33,     6,    22,    12,   215,    28,    77,
          52,     5,    14,   407,    16,    82, 10311,     8,     4,
         107,   117,  5952,    15,   256,     4, 31050,     7,  3766,
           5,   723,

In [33]:
import tensorflow
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Embedding,Dense,Flatten,SimpleRNN

In [34]:
model=Sequential()

model.add(SimpleRNN(32,input_shape=(200,1),return_sequences=False))
model.add(Dense(1,activation='sigmoid'))
model.summary()


/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [35]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

model.fit(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 34s 40ms/step - accuracy: 0.5103 - loss: 0.7218 - val_accuracy: 0.4978 - val_loss: 0.6944
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 45s 45ms/step - accuracy: 0.5106 - loss: 0.6930 - val_accuracy: 0.4985 - val_loss: 0.6940
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 35s 37ms/step - accuracy: 0.5059 - loss: 0.6926 - val_accuracy: 0.4959 - val_loss: 0.6943
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 29s 37ms/step - accuracy: 0.5077 - loss: 0.6930 - val_accuracy: 0.4998 - val_loss: 0.6943
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 45s 42ms/step - accuracy: 0.4977 - loss: 0.6936 - val_accuracy: 0.5006 - val_loss: 0.6941
