In [ ]:
import torch
print(torch.__version__)

2.8.0+cu126


In [ ]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU:{torch.cuda.get_device_name(0)}")

else:
  print("GPU is not available")

GPU is not available


**Creating tensors**

In [ ]:
a=torch.empty(2,3)
a

tensor([[4.4653e+30, 1.6931e+22, 1.8494e+31],
        [2.8231e+23, 1.1868e+27, 1.1626e+27]])

In [ ]:
type(a)

torch.Tensor

In [ ]:
a=torch.zeros(2,3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
a=torch.ones(2,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
a=torch.rand(2,3)
a

tensor([[0.2823, 0.7844, 0.7936],
        [0.3252, 0.7804, 0.7473]])

In [ ]:
# when we re run the code of the torch.rand each time it winll give thenew vaulues to remove this ambiguity we use the manual_Seed function

In [ ]:
torch.manual_seed(100)
a=torch.rand(2,3)
a

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# custom sensor
a=torch.tensor([[1,2,3],[4,5,6]])
a

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# some other methods for declaring the tensors
print("Using arange :",torch.arange(0,10,2))

print("Using linspacce: ",torch.linspace(0,10,10))

print("using eye:",torch.eye(5,5))

print("using full:",  torch.full((3,3),5))

Using arange : tensor([0, 2, 4, 6, 8])
Using linspacce:  tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye: tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full: tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


**Shape of the tensors**

In [ ]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
# to copy thr shape pf the tensor
torch.empty_like(x)


tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)
torch.zeros_like(x)


tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.rand_like(x)

**twnsor datatypes**

In [ ]:
x.dtype

torch.int64

In [ ]:
torch.tensor([1,2,3],dtype=torch.float32)


tensor([1., 2., 3.])

In [ ]:
# to change the datatype of the existing tensor
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
x=torch.rand(2,2)
x

tensor([[0.2627, 0.0428],
        [0.2080, 0.1180]])

In [ ]:
x+2
#
x-2
#
x**2
#
x*3
#
x/4
#
(x*100)//3
#
(x*100)%3

tensor([[2.2691, 1.2840],
        [2.8029, 2.8037]])

In [ ]:
a=torch.rand(2,2)
b=torch.rand(2,2)
a+b

tensor([[1.2722, 0.7364],
        [1.0334, 1.1238]])

In [ ]:
a-b
a*b
a/b
a%b
a**b

tensor([[0.8558, 0.8380],
        [0.3262, 0.8600]])

In [ ]:
c=torch.tensor([1,-2,-4,3])
c.abs()

tensor([1, 2, 4, 3])

In [ ]:
torch.clamp(c,min=-1,max=2)
c

tensor([ 1, -2, -4,  3])

**Reduction operations**

In [ ]:
e=torch.randint(size=(2,3),low=2,high=10,dtype=torch.float32)
e

tensor([[3., 7., 7.],
        [5., 6., 6.]])

In [ ]:
# to get the product
torch.prod(e)

tensor(26460.)

In [ ]:
# sum of all elemments of the matrix
torch.sum(e)

# along rows
torch.sum(e,dim=1)

# along cols
torch.sum(e,dim=0)

tensor([ 8., 13., 13.])

In [ ]:
# mean
torch.mean(e)

# along cols
torch.mean(e,dim=0)

# along rows
torch.mean(e,dim=1)

tensor([5.6667, 5.6667])

In [ ]:
torch.median(e)
torch.max(e)
torch.min(e)

tensor(3.)

In [ ]:
# standard deviation
torch.std(e)

# variance
torch.var(e)

# returnr the index vlaue of the largets numbner
torch.argmax(e)
torch.argmin(e)

tensor(1)

**Matrix multiplication**

In [ ]:
f=torch.randint(size=(2,3),low=2,high=10,dtype=torch.float32)
g=torch.randint(size=(3,2),low=2,high=10,dtype=torch.float32)


In [ ]:
# matric multip;ication
torch.matmul(f,g)

tensor([[ 42.,  62.],
        [ 78., 107.]])

dot product


In [ ]:
vec1=torch.tensor([1,2,3])
vec2=torch.tensor([4,5,6])

torch.dot(vec1,vec2)

# tranpose
torch.transpose(f,0,1)

# determinnat
h=torch.randint(size=(3,3),low=2, high=5,dtype=torch.float32)
torch.det(h)
# inverse
torch.inverse(h)

tensor([[-0.2500,  0.5000, -0.2500],
        [-0.5000,  0.0000,  0.5000],
        [ 1.2500, -0.5000, -0.2500]])

comparison operations


In [ ]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[0, 8, 4],
        [7, 2, 3]])
tensor([[8, 5, 6],
        [2, 9, 5]])


In [ ]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

special functions

In [ ]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 4., 2.],
        [7., 1., 1.]])

In [ ]:
# log
torch.log(k)

# exp
torch.exp(k)


# sqrt
torch.sqrt(k)

# sigmoid
torch.sigmoid(k)


# softmax
torch.softmax(k, dim=0)


# relu
torch.relu(k)

inplace operations

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])
tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])


In [ ]:
m.add_(n)

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [ ]:
m.relu()

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

copying a tensor


In [ ]:
a = torch.rand(2,3)
a

In [ ]:
b=a
b

In [ ]:
a[0][0]=0
a

In [ ]:
id(a)
id(b)

In [ ]:
b=a.clone()

In [ ]:
# ternsors operations on gpu


In [1]:
import torch
torch.cuda.is_available()

True

In [3]:
device=torch.device("cuda")
device

device(type='cuda')

In [4]:
a=torch.rand((2,3),device=device)
a

tensor([[0.4460, 0.2364, 0.2058],
        [0.4473, 0.2278, 0.5558]], device='cuda:0')

In [5]:
b=torch.rand(2,4)
b

tensor([[0.8540, 0.8851, 0.6335, 0.8567],
        [0.4743, 0.7721, 0.8559, 0.0630]])

In [6]:
c=a.to(device)
c

tensor([[0.4460, 0.2364, 0.2058],
        [0.4473, 0.2278, 0.5558]], device='cuda:0')

In [7]:
c+2

tensor([[2.4460, 2.2364, 2.2058],
        [2.4473, 2.2278, 2.5558]], device='cuda:0')

In [8]:
import time
size=10000

matrix_cpu1=torch.randn(size,size)
matrix_cpu2=torch.randn(size,size)

start_time=time.time()
result_cpu=torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time=time.time()-start_time


matrix_gpu1=matrix_cpu1.to('cuda')
matrix_gpu2=matrix_cpu2.to('cuda')


startr_time=time.time()
result_gpu=torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize()
gpu_time=time.time()-start_time

print(f"CPU time: {cpu_time}")
print(f"GPU time: {gpu_time}")

CPU time: 17.668381452560425
GPU time: 18.57832980155945


reshaping tensors

In [9]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [10]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [11]:
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
b=torch.rand(2,3,4)
b

tensor([[[0.5477, 0.0151, 0.2109, 0.5271],
         [0.8685, 0.2443, 0.7415, 0.2213],
         [0.4599, 0.8423, 0.2090, 0.1488]],

        [[0.4650, 0.0521, 0.4944, 0.9106],
         [0.0798, 0.2672, 0.9350, 0.4572],
         [0.8885, 0.9104, 0.5088, 0.6802]]])

In [13]:
# permute
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [14]:
# unsqueeeze
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [15]:
# squeeeze
d=torch.rand(1,226,226,3)
d.squeeze(0).shape

torch.Size([226, 226, 3])

numpy to tensors

In [16]:
import numpy as np
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [17]:
b=a.numpy()
type(b)

numpy.ndarray

In [19]:
c=np.array([1,2,3,4])
torch.from_numpy(c)

tensor([1, 2, 3, 4])