In [1]:
import torch
import torch.nn as nn

In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear=nn.Linear(num_features,1)
    self.sigmoid=nn.Sigmoid()


  def forward(self, features):
    out =self.linear(features)
    out=self.sigmoid(out)
    return out


In [ ]:
features=torch.rand(10,5)
model=Model(features.shape[1])
print(model(features))

tensor([[0.5753],
        [0.5417],
        [0.5702],
        [0.5399],
        [0.5488],
        [0.5789],
        [0.6050],
        [0.5932],
        [0.5543],
        [0.5711]], grad_fn=<SigmoidBackward0>)


In [ ]:
model.linear.weight
model.linear.bias

Parameter containing:
tensor([0.3047], requires_grad=True)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
#.
#.  .
#.  .   .-->y_pred
#.  .
#.

In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.linear1=nn.Linear(num_features,3)
    # self.sigmoid=nn.Sigmoid()
    self.relu=nn.ReLU()
    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()


  def forward(self, features):
    out =self.linear(features)
    out=self.relu
    return out


In [ ]:
features=torch.rand(10,5)
model=Model(features.shape[1])
print(model(features))

tensor([[0.4392],
        [0.4523],
        [0.4467],
        [0.4339],
        [0.4474],
        [0.4530],
        [0.4436],
        [0.4464],
        [0.4498],
        [0.4406]], grad_fn=<SigmoidBackward0>)


In [ ]:
model.linear1.weight
model.linear2.weight

Parameter containing:
tensor([[ 0.2494,  0.1694, -0.5256]], requires_grad=True)

In [ ]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

imporoving the forward method  with the sequential container

In [ ]:
class Model(nn.Module):
  def __init__(self,num_features):

    super().__init__()
    self.network=nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )


  def forward(self, features):
    out =self.network(features)
    return out
